language: objective-c
osx_image: xcode9
env:
  global:
  - WORKSPACE="HyperioniOSExtension.xcworkspace"
  matrix:
    - DESTINATION="OS=9.0,name=iPhone 5s"           SCHEME="HYPEnvironmentSelector"   POD_LINT="NO"
    - DESTINATION="OS=10.0,name=iPhone 6s"          SCHEME="HYPFPSMonitor"            POD_LINT="NO"
    - DESTINATION="OS=11.1,name=iPhone 8 Plus"      SCHEME="HYPEnvironmentSelector"   POD_LINT="NO"
    - DESTINATION="OS=11.3,name=iPhone X"           SCHEME="Example"                  POD_LINT="YES"

before_install:
  - gem install cocoapods
  - pod repo update
  - pod install

script:
  - env
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcpretty --version

  # Build Framework in Debug and Run Tests if specified
  - xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" | xcpretty

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi
