
platform :ios, "9.0"

use_frameworks!
inhibit_all_warnings!

target 'HyperioniOSExtensionDemo' do
    pod 'HyperioniOSExtension/EnvironmentSelector',  :path => '../', :configurations => ['Debug', 'Test']
    pod 'HyperioniOSExtension/FPSMonitor',           :path => '../', :configurations => ['Debug', 'Test']
    pod 'HyperioniOSExtension/UIMainThreadChecker',  :path => '../', :configurations => ['Debug', 'Test']
end

